### PR TITLE
Catalyst core theme unit testing implemented with Jest snapshot testing

### PR DESCRIPTION
**Pull request by duncanjbain**
I've implemented unit testing on the core theme using Jest with snapshot testing.

I'm not sure if performing unit testing is the direction you want to go, but thought it might be a good idea to this implemented before proceeding with end to end testing.

Let me know your thoughts!

### CODE REVIEW

**Comment by ehowey** [comment]
Sounds amazing!  I will try to look over it later tonight or tommorow!  Thank you for all of your work on this!

**Comment by duncanjbain** [comment]
> Sounds amazing!  I will try to look over it later tonight or tommorow!  Thank you for all of your work on this!
> […](#)
> On Feb 1, 2020, 12:46 PM -0700, Duncan Bain ***@***.***>, wrote: I've implemented unit testing on the core theme using Jest with snapshot testing. I'm not sure if performing unit testing is the direction you want to go, but thought it might be a good idea to this implemented before proceeding with end to end testing. Let me know your thoughts! You can view, comment on, or merge this pull request online at: #393 Commit Summary • Added Jest to devDepends • Set up default Jest conf • Jest default config for Gatsby • Jest to ignore cypress dir, added header test to check if jest works • Moved jest stuff into own subdir. Added jest script to package.json • Added footer component snapshot test • added site meta data mock data, added content-container test • added test for main component • added site-container component test • added snapshot test for layout component File Changes • A jest/__mocks__/file-mock.js (1) • A jest/__mocks__/gatsby.js (27) • A jest/__mocks__/site-config.js (18) • A jest/__mocks__/site-metadata.js (38) • A jest/jest-preprocess.js (4) • A jest/jest.config.js (19) • A jest/loadershim.js (3) • M package.json (8) • A themes/gatsby-theme-catalyst-core/src/components/__snapshots__/content-container.test.js.snap (9) • A themes/gatsby-theme-catalyst-core/src/components/__snapshots__/footer.test.js.snap (12) • A themes/gatsby-theme-catalyst-core/src/components/__snapshots__/header.test.js.snap (12) • A themes/gatsby-theme-catalyst-core/src/components/__snapshots__/layout.test.js.snap (37) • A themes/gatsby-theme-catalyst-core/src/components/__snapshots__/main.test.js.snap (9) • A themes/gatsby-theme-catalyst-core/src/components/__snapshots__/site-container.test.js.snap (9) • A themes/gatsby-theme-catalyst-core/src/components/content-container.test.js (17) • A themes/gatsby-theme-catalyst-core/src/components/footer.test.js (11) • A themes/gatsby-theme-catalyst-core/src/components/header.test.js (12) • A themes/gatsby-theme-catalyst-core/src/components/layout.test.js (30) • A themes/gatsby-theme-catalyst-core/src/components/main.test.js (17) • A themes/gatsby-theme-catalyst-core/src/components/site-container.test.js (17) • M themes/gatsby-theme-catalyst-core/src/utils/normalize-css.js (2) • M yarn.lock (1313) Patch Links: • https://github.com/ehowey/gatsby-theme-catalyst/pull/393.patch • https://github.com/ehowey/gatsby-theme-catalyst/pull/393.diff — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

No worries! 😃 

It's a pretty simple set of tests, it just renders the component and creates a snapshot of the output, when the tests are ran again the outputs are checked against these snapshots. If these tests pass then it'll give confidence moving forward onto end to end testing.

It was a nice introduction into using Jest though!

**Comment by ehowey** [comment]
Hi Duncan,

I have been thinking about this a bit tonight, and doing some of my own research on testing and Jest. To be honest I don't really know much about testing either. One of my thoughts is about how to best handle testing overall. I know that Jest and Cypress can be used in unison together, one is E2E, one is unit testing. Here are some things on my mind, would love your feedback on it.

- How is this going to be for long term maintenance? This is a side project for me/passion project. I worry about maintaining and caretaking the tests over the long term.  Do you have any sense of what this would be like with Jest?
- Do we actually need both Cypress and Jest? Would one be better suited than the other?
- How can we use a Github Action to automatically test any PRs using the tests? I believe this is possible and you can avoid having to use something like CircleCI/TravisCI. Again from my perspective the simpler the better at least at this stage.

I think for me the biggest worry is about long term maintenance and overall ease of use. Would love to know what you think about this or if you have any experience with this.  I will post here if I have some more thoughts. In some ways this PR is provoking a need to think about the scope of testing overall.  I know it LekoArts they are using both and have a sort of similar monorepo setup.

https://github.com/LekoArts/gatsby-themes

**Comment by duncanjbain** [comment]
Hi @ehowey 

I'm pretty new to React development and testing in general, so I might be off the mark with some of my thoughts! My main source of information came from the Gatsby documentation which starts you off with unit testing with Jest via snapshots so I figured it might be worth giving these a look as they seemed pretty straight forward to implement.

The tests I've implemented are pretty simple to create and maintain. They should only require attention when they fail, which is more than likely down to a deliberate change made in the way the component is rendered.

After doing a bit of digging, I think Cypress can also do snapshot testing which would make Jest a bit redundant if that's the case.

It definitely looks like Cypress testing with Github Actions is possible. https://www.cypress.io/blog/2019/11/20/drastically-simplify-your-testing-with-cypress-github-action/

Funnily enough I did look at LekoArts to see if they had implemented testing, and it looked like they used Cypress without any snapshot testing.

I think the best way forward is probably just using Cypress for end to end testing in a similar fashion to LekoArts, and not using Jest to carry out any snapshot testing. This would only mean one set of tests to create and maintain.

**Comment by ehowey** [comment]
Hey Duncan,

I took a look tonight, great work! They all passed! 

Unfortunately I don't know enough about testing to merge at this time but I am keen to think this through, and really value your feedback and perspective. Let's think of this as a work in progress. I want to have some more robust tests before going to v1.0 but need to do more learning before committing to a route. 

I saw that same blog post about Cypress a while back, seems like you can maybe also do that with Jest as well from what I have been reading. I am going to just leave this PR open for a while, as a place to house a bit of discussion in general about testing for this repo. Maybe do a bit of experimenting with GH Actions and see what I can make happen with Cypress or Jest.  I know a bit more about Cypress but it seems like Jest is great as well.  You did a lot of work here and I really appreciate it.

Feel free to chime in and let me know what you think.

**Comment by ehowey** [comment]
Hey Duncan - Where do you stand on this now? I have tests setup to run on PRs now, if you wanted to expand and add some other tests you would be welcome to.  I think I will keep this repo in the Cypress ecosystem though.

**Comment by ehowey** [comment]
Addressed with: https://github.com/ehowey/gatsby-theme-catalyst/pull/427

Thanks for your thinking and work you put into this Duncan!

**Pull request closed without merging**
