### PR TITLE
improve post footer styles and format in blog themes

### PR DESCRIPTION
**Pull request by AlexHff**
Fixes ehowey/gatsby-theme-catalyst#840

### CODE REVIEW

**Comment by ehowey** [comment]
Hey! Thanks for submitting this! I will take a look in the next few days and let you know any feedback before we merge it! Just at work now so I can't look until tonight. 

Super excited to have your contribution!

**Comment by ehowey** [comment]
@AlexHff - I took a look tonight!

First of all - thank-you for catching the missing keys in the map method - oi! I am sorry I missed those.  I merged those in already.

Secondly - I like the direction you are headed with the post-footer. I was thinking of something similar. But I think we can improve the design a bit more before merging. Let's use this branch/PR and work on it together. I probably won't have much time until this weekend to really sit down and work on it in as much detail as I would want but am looking forward to seeing what we can come up with. Having said that, please feel free to update this PR with any additional work you do or additional ideas.

**Comment by ehowey** [comment]
I whipped up some minor improvements and have merged them in. Take a look let me know what you think!

**Comment by AlexHff** [comment]
Hi, I'll take a look at the changes this weekend. Looking forward to improving the template!

**Comment by ehowey** [comment]
Sounds good! Let me know how it goes or if you have any questions!

**Comment by AlexHff** [comment]
All of this looks good to me, but I though you wanted to have a featured image in the post footer. Did you change your mind about this?

**Comment by ehowey** [comment]
Hi @AlexHff I think maybe what is best is to do it on just gatsby-theme-catalyst-helium and then this provides an example for others to easily extend with component shadowing. That way it is more of an opt-in option?

I for sure want to leave catalyst-bery as plain text. 

I was thinking about also including the date too? Or do you think just the title and image?

What do you think?

**Comment by AlexHff** [comment]
I think title + featured image is good. We can try date to see how it looks. I'll rebase and work on it.

**Comment by ehowey** [comment]
Sounds good - no stress!

**Comment by ehowey** [comment]
Hi @AlexHff I assume this has gone stale for you - feel free to reopen if you would like!

Hope you are doing well, have a good day!

**Pull request closed without merging**
